### ISSUE TITLE
Headlines feedback

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove-oc4ids#10]
Testing with the example OC4IDS file from the documentation results in the following headlines:

![image](https://user-images.githubusercontent.com/19265814/60635515-fe034700-9e0a-11e9-8840-a67af15c9b23.png)

1. Change 'OC4IDS record package schema'  to 'OC4IDS project package schema'

![image](https://user-images.githubusercontent.com/19265814/60635587-34d95d00-9e0b-11e9-98d2-b5d7e24f228d.png)

2. Add missing version number

![image](https://user-images.githubusercontent.com/19265814/60635591-3a36a780-9e0b-11e9-9abc-9c160b62dbb2.png)

3. Change 'record' to 'project' and add missing count

![image](https://user-images.githubusercontent.com/19265814/60635636-58040c80-9e0b-11e9-9d09-5e8810a1bd6d.png)

4. Remove unique OCID count

![image](https://user-images.githubusercontent.com/19265814/60635650-618d7480-9e0b-11e9-8b7a-282fb5213bb0.png)

**Comment by duncandewhurst** [comment]
Sorry, a couple more:

5. Use 'licence' rather than 'license'

![image](https://user-images.githubusercontent.com/19265814/60638542-ed71c180-9e48-11e9-8d85-f83db30d4e25.png)

Good if we can also fix that in OCDS CoVE

6. Add a link to the publication policy, per https://github.com/OpenDataServices/cove/issues/1194

**Comment by duncandewhurst** [comment]
Actually, sorry - scratch 5. I forgot we are supposed to use american english for OCDS

**Comment by duncandewhurst** [comment]
6. is the only outstanding item

**Comment by michaelwood** [comment]
Fixes merged
