### ISSUE TITLE
Landing page UI improvements

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove-oc4ids#19]
* Decrease the font size of the headers (at least to fit OC4IDS on one line)
* Replace "Standard Documentation" with "OC4IDS Documentation"
* Swap the positions of the "Check and review" and "About OC4IDS" blocks (ideally, "About OC4IDS" would come after both blocks, as it's the least relevant content)
  * This is true for the OCDS review tool as well; lead with the most relevant content
* Typo: OC4DS (should be OC4IDS)
* Clicking "sample data" should lead to review results, not link directly to the data #14
* The hyperlinks in the footer do not have a clearly distinct color from text
* The form prompts can be improved so that a first time user knows what to do without scrolling below the fold to read the instructions, e.g. "Upload an OC4IDS project package" instead of simply "Upload". I'm not including a full review here.
  * This is true for the OCDS review tool as well

**Comment by michaelwood** [comment]
> * Typo: OC4DS (should be OC4IDS)
> * Replace "Standard Documentation" with "OC4IDS Documentation"

Done pending review

> * Decrease the font size of the headers (at least to fit OC4IDS on one line)
> * Swap the positions of the "Check and review" and "About OC4IDS" blocks (ideally, "About OC4IDS" would come after both blocks, as it's the least relevant content)
>   
>   * This is true for the OCDS review tool as well; lead with the most relevant content

> * Clicking "sample data" should lead to review results, not link directly to the data #14
> * The hyperlinks in the footer do not have a clearly distinct color from text
> * The form prompts can be improved so that a first time user knows what to do without scrolling below the fold to read the instructions, e.g. "Upload an OC4IDS project package" instead of simply "Upload". I'm not including a full review here.
>   
>   * This is true for the OCDS review tool as well

These issues are currently not in scope for this current sprint, I have opened a separate issue to keep track of these for the future. Let us know if there are any blockers to going live. Thanks
