### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/cove-oc4ids#2]
1. Change title from 'Open Contracting for Infrastructure Standards' to 'Open Contracting for Infrastructure Data Standard'

![image](https://user-images.githubusercontent.com/19265814/59905987-74fa1200-93ff-11e9-9faf-1747a65b50b3.png)

2. Make 'Review' lowercase

![image](https://user-images.githubusercontent.com/19265814/59906023-8c38ff80-93ff-11e9-9a7b-2de7e1abcaee.png)

3. Make 'Data Review Tool' upper case

![image](https://user-images.githubusercontent.com/19265814/59906050-9824c180-93ff-11e9-91b9-b3443066dbe9.png)

4. Change 'Open Contracting' to 'Open Contracting Partnership', add a link to '[CoST - the Infrastructure Transparency Initiative](http://infrastructuretransparency.org/), change 'Open Contracting for Infrastructure Data Standard' to 'Open Contracting for Infrastructure Data Standards Toolkit'

![image](https://user-images.githubusercontent.com/19265814/59906137-de7a2080-93ff-11e9-839a-36303548637e.png)

5. Check flattening behaviour supports round tripping

Flattening a JSON project package containing a single project, results in a spreadsheet version which has two projects ([example](http://oc4ids.cove.dev.opendataservices.coop/data/94c09bfa-63d7-41c1-ab11-0a83db4b19da):

* Source JSON file contains one project:

![image](https://user-images.githubusercontent.com/19265814/59906342-6c560b80-9400-11e9-87ef-fdf4a6615414.png)

* Result JSON file after flattening and then unflattening contains two projects:

![image](https://user-images.githubusercontent.com/19265814/59906368-7ed04500-9400-11e9-8467-4ad2afaad722.png)

6. Remove BODS statistics

![image](https://user-images.githubusercontent.com/19265814/59906392-91e31500-9400-11e9-8da3-15c9f5f3db86.png)

7. Remove exclamation marks

![image](https://user-images.githubusercontent.com/19265814/59906540-dd95be80-9400-11e9-84bd-8b9e238b6e29.png)

8. Include child properties in additional field feedback

![image](https://user-images.githubusercontent.com/19265814/59906657-2baac200-9401-11e9-816e-170913f5908f.png)

**Comment by michaelwood** [comment]
Thanks for the report. These issues should be addressed by the latest updates and are now testable on the [dev instance](http://oc4ids.cove.dev.opendataservices.coop/).  Feel free to reopen if issues persist.

**Comment by duncandewhurst** [comment]
flattening issue persists (flattening a JSON project package containing a single project, results in a spreadsheet version which has two projects)

try flattening the [example oc4ids file](http://standard.open-contracting.org/infrastructure/latest/en/_static/example.json) from the documentation and then unflattening the resulting file and you will see the issue

**Comment by duncandewhurst** [comment]
This has been resolved, though I noted another issue with unflattening which I've logged in #'15
