### ISSUE TITLE
Results page UI improvements

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/cove-oc4ids#20]
I used this for invalid data: https://gist.githubusercontent.com/pindec/4c09afc85bde80fb001a2360b7e7ee83/raw/80968a87891431b3d5cf606f144f99d2e0a1b471/validation_errors_oc4ids_package.json

* Add whitespace between download icon and links
* Add "The schema version specified in the file is …" as in OCDS DRT
* Add a period to "There were no validation errors" and "There were no additional fields" (see later bullet about use of "validation")
* Regarding "We have tried to convert your JSON into a spreadsheet format. The results can be seen below." Is it possible to try and not succeed? What would the output look like in that case? I think it'd be better to describe the purpose of the files instead (adapting content from the landing page), e.g.: "Download the data you submitted in either its original or alternative format. If you are investigating an error, you might find the Excel format easier to use."
  * This is true for the OCDS review tool as well
* In general, replace all occurrences of words whose root is "valid". For example, replace "Validation Errors" with "Structural Errors". See the OCDS DRT for preferred terminology.
* First 3 Examples: If the value is a string, it should be surrounded by quotation marks. This makes it easier to see that e.g. 500 is `"500"` instead of `500`. It also means something will be printed to the screen for the empty string (`""` instead of nothing).
  * This is true for the OCDS review tool as well
* "… is missing but required within releases" is repeated for different indices within an array, instead of collected into one row.

**Comment by michaelwood** [comment]
[Done = In pull request/review]

>Add whitespace between download icon and links
>Add "The schema version specified in the file is …" as in OCDS DRT
>Add a period to "There were no validation errors" and "There were no additional fields" (see later bullet about use of "validation")

Done

>Regarding "We have tried to convert your JSON into a spreadsheet format. The results can be seen below." Is it possible to try and not succeed? What would the output look like in that case? I think it'd be better to describe the purpose of the files instead (adapting content from the landing page), e.g.: "Download the data you submitted in either its original or alternative format. If you are investigating an error, you might find the Excel format easier to use."

I've changed this to:
"
Alternative formats for reviewing your data.

Conversion of your (JSON) data into a spreadsheet format. The results can be seen below.
"
Hope this is OK, this keeps it open and short whilst still allowing for the error case where the results section becomes a list of errors

>This is true for the OCDS review tool as well

Please could you raise an issue on ocds review tool for that. Thanks

>In general, replace all occurrences of words whose root is "valid". For example, replace "Validation Errors" with "Structural Errors". See the OCDS DRT for preferred terminology.

Done

>First 3 Examples: If the value is a string, it should be surrounded by quotation marks. This makes it easier to see that e.g. 500 is "500" >instead of 500. It also means something will be printed to the screen for the empty string ("" instead of nothing).
>This is true for the OCDS review tool as well

These messages come from lower down the 'stack' in lib-cove/web and would need to be investigated as part of some different work on lib-cove (rather than oc4ids). 

>"… is missing but required within releases" is repeated for different indices within an array, instead of collected into one row.

I am not sure cove currently has the ability to collate this. I will check with @kindly

**Comment by michaelwood** [comment]
As with issue #19 remaining issues now added to issue #29
