### ISSUE TITLE
More Feedback

### ISSUE THREAD

**Issue by kindly** [OpenDataServices/cove-oc4ids#7]
@jpmckinney @duncandewhurst 

We have published the latest oc4ids code here
http://oc4ids.cove.dev.opendataservices.coop/

Any minor feedback could be left in this issue whilst any bigger feedback in new issues.  

Current status of the project can be found:
https://github.com/orgs/OpenDataServices/projects/5

**Comment by duncandewhurst** [comment]
Thanks @kindly when do you need feedback by for it be addressed in this sprint?

cc @michaelwood

**Comment by michaelwood** [comment]
We scheduled up to the 9th July for this sprint. So ideally feedback as much before then as possible!

**Comment by duncandewhurst** [comment]
Thanks @michaelwood @kindly 

I have reviewed and I think the main outstanding thing is to get some draft copy on the landing page,  I suggest using the copy from OCDS CoVE and replacing 'OCDS' -> 'OC4IDS' and 'contracting process' -> 'project' etc. as a starting point, I can then review and suggest further tweaks.

I've reopened #2 as the flattening issue persists and have opened #10 with some feedback on the headlines.

I've also made a PR(https://github.com/OpenDataServices/cove-oc4ids/pull/9) to reorder the links in the footer.

The other thing I noticed is we are reporting that all additional checks passed:

![image](https://user-images.githubusercontent.com/19265814/60636238-9995b700-9e0d-11e9-9b47-83d0cf385b11.png)

Is OC4IDS CoVE actually performing additional checks? If not, can we remove that box please.

Finally, if possible it would be good to include a fix for https://github.com/OpenDataServices/cove/issues/1188 in the first version of OC4IDS CoVE.

I haven't checked exhaustively that every single error in the broken file prepared by @pindec is reported in CoVE, do we have an automated test for that or does someone need to review CoVE output manually?

**Comment by michaelwood** [comment]
> Thanks @michaelwood @kindly
> 
> I have reviewed and I think the main outstanding thing is to get some draft copy on the landing page, I suggest using the copy from OCDS CoVE and replacing 'OCDS' -> 'OC4IDS' and 'contracting process' -> 'project' etc. as a starting point, I can then review and suggest further tweaks.
> 

Great this is now in pull request #11 

> I've reopened #2 as the flattening issue persists and have opened #10 with some feedback on the headlines.
> 

Ack, sorry, we did fix this but I didn't push it to the repository. Have opened a new pull request on lib-cove-oc4ids https://github.com/OpenDataServices/lib-cove-oc4ids/pull/8

> I've also made a PR(#9) to reorder the links in the footer.
> 

Merged thanks!

> The other thing I noticed is we are reporting that all additional checks passed:
> 
> ![image](https://user-images.githubusercontent.com/19265814/60636238-9995b700-9e0d-11e9-9b47-83d0cf385b11.png)
> 
> Is OC4IDS CoVE actually performing additional checks? If not, can we remove that box please.
> 

No there are no additional checks being performed so I've removed the box. Pull request #11 

> Finally, if possible it would be good to include a fix for [OpenDataServices/cove#1188](https://github.com/OpenDataServices/cove/issues/1188) in the first version of OC4IDS CoVE.
> 

This is work that I also have a pull request in review for as it was requested for Open Contracting anyway. It is likely to need quite a bit of thought/review/testing as it has potential to impact on quite a few things. https://github.com/OpenDataServices/lib-cove/pull/24

> I haven't checked exhaustively that every single error in the broken file prepared by @pindec is reported in CoVE, do we have an automated test for that or does someone need to review CoVE output manually?

The automated test currently running uses the broken file and works how many of each category of validation errors there should be and compares this to the output of the validation.  So this should be quite a good sanity test. https://github.com/OpenDataServices/lib-cove-oc4ids/blob/master/tests/test_api.py .

**Comment by duncandewhurst** [comment]
All resolved, thanks!
